// src/components/SlideComponent.vue
<template>
  <section class="slide-wrapper" @pointerdown="activatePointer" @pointerup="deactivatePointer"
           @pointermove="pointerMove" @pointerleave="deactivatePointer">
    <figure class="slide" :style="styleAttribute" ref="slide">
      <img src="../assets/cat-small.jpg" alt="background-image" class="slide-background slide-background--is-slideable" ref="image">
      <figcaption class="slide-content">
        Caption
      </figcaption>
    </figure>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class SlideComponent extends Vue {
  private pointerIsDown: boolean = false;
  private translateX: number = 0;

  private activatePointer() {
    this.pointerIsDown = true;
  }

  private deactivatePointer() {
    this.pointerIsDown = false;
  }

  private pointerMove(event: PointerEvent) {
    if (!this.pointerIsDown) {
      return
    }

    const container = this.$refs.slide as HTMLElement;
    const image = this.$refs.image as HTMLElement;

    const boundingBoxContainer = container.getBoundingClientRect();
    const width = boundingBoxContainer.width;
    const offsetLeft = container.offsetLeft;

    const overflowSize = Math.abs(image.offsetLeft);

    const pointerX = event.x;

    const currentPositionInPercent = Math.round((pointerX - offsetLeft) * 100 / width);
    const maxTransformX = Math.round(overflowSize * 100 / width);
    const elongationFromCenterAbsolute = (currentPositionInPercent - 50) * 2;

    //slightly long variable name
    const elongationFromCenterMappedToOverflowSize = (maxTransformX * elongationFromCenterAbsolute) / 100;

    this.translateX = elongationFromCenterMappedToOverflowSize;
  }

  get styleAttribute() {
    return {
      transform: `translateX(${this.translateX}%)`,
    };
  }
}
</script>

<style scoped lang="scss">
.slide-wrapper {
  margin: 2rem 0;
  padding: 0;
  background: aliceblue;
  overflow: hidden;
}

.slide {
  position: relative;
  margin: 0;
  padding: 0;
  transform: translateX(0);
  will-change: transform;
  touch-action: none;
}

.slide-background {
  display: block;
  width: 100%;
  height: auto;
  pointer-events: none;

  &--is-slideable {
    $width: 150%;
    $overflow-width: $width - 100%;

    width: $width;
    margin-left: ($overflow-width / 2) * -1;
    margin-right: ($overflow-width / 2) * -1;
  }
}

.slide-content {
  position: absolute;
  left: 1rem;
  right: 1rem;
  bottom: 1rem;
  text-align: center;
  background: #fff;
}
</style>

// sveltekit-temp/src/routes/slide-component/+page.svelte
<script lang="ts">
  import { faker } from '@faker-js/faker';
  import { onMount } from 'svelte';

  let pointerIsDown;
  let translateX = 0;
  let container;
  let image;

  function activatePointer(): void {
    pointerIsDown = true;
  }

  function deactivatePointer(): void {
    pointerIsDown = false;
  }

  function pointerMove(event): void {
    if (!pointerIsDown) {
      return
    }

    const boundingBoxContainer = container.getBoundingClientRect();
    const width = boundingBoxContainer.width;
    const offsetLeft = container.offsetLeft;

    const overflowSize = Math.abs(image.offsetLeft);

    const pointerX = event.x;

    const currentPositionInPercent = Math.round((pointerX - offsetLeft) * 100 / width);
    const maxTransformX = Math.round(overflowSize * 100 / width);
    const elongationFromCenterAbsolute = (currentPositionInPercent - 50) * 2;

    const elongationFromCenterMappedToOverflowSize = (maxTransformX * elongationFromCenterAbsolute) / 100;
    translateX = elongationFromCenterMappedToOverflowSize;
  }

</script>

<section>
  <h2 class="text-xl pb-4">Slide component</h2>
  <p class="pb-4">{faker.lorem.lines()}</p>
  <div class="m-0 p-0 overflow-hidden"
    on:pointerdown={activatePointer}
    on:pointerup={deactivatePointer}
    on:pointermove={pointerMove}
    on:pointerleave={deactivatePointer}
  >
    <figure bind:this={container} class="relative select-none touch-none" style="translate: {translateX}% 0;">
      <img src={faker.image.cats(960, 640, false)} bind:this={image} class="w-[150%] ml-[-25%] mr-[-25%] max-w-none pointer-events-none" alt="Cat">
      <figcaption class="absolute inset-x-4 bottom-4 text-center bg-white">
        Meow!
      </figcaption>
    </figure>
  </div>

</section>
