// src/components/SensorSlideComponent.vue
<template>
  <section class="slide-wrapper">
    <figure class="slide" :style="styleAttribute" ref="slide">
      <img src="../assets/cat2-small.jpg" alt="background-image" class="slide-background slide-background--is-slideable" ref="image">
      <figcaption class="slide-content">
        Meow!
      </figcaption>
    </figure>
  </section>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class SensorSlideComponent extends Vue {
  private translateX: number = 0;

  private orientationChangEvent(event: DeviceOrientationEvent) {
    const rotationX = event.alpha;

    const container = this.$refs.slide as HTMLElement;
    const image = this.$refs.image as HTMLElement;

    if (typeof container === 'undefined' || typeof image === 'undefined') {
        return;
    }

    const boundingBoxContainer = container.getBoundingClientRect();
    const width = boundingBoxContainer.width;

    const overflowSize = Math.abs(image.offsetLeft);

    const maxTransformX = Math.round(overflowSize * 100 / width);
    const elongationFromCenterAbsolute = (rotationX * 100) / 180;

    //slightly long variable name
    const elongationFromCenterMappedToOverflowSize = (maxTransformX * elongationFromCenterAbsolute) / 100;

    this.translateX = elongationFromCenterMappedToOverflowSize;
  }

  private created () {
    window.addEventListener('deviceorientation', this.orientationChangEvent, true);
  }

  get styleAttribute() {
    return {
      transform: `translateX(${this.translateX}%)`,
    };
  }
}
</script>

<style scoped lang="scss">
.slide-wrapper {
  margin: 2rem 0;
  padding: 0;
  background: aliceblue;
  overflow: hidden;
}

.slide {
  position: relative;
  margin: 0;
  padding: 0;
  transform: translateX(0);
  will-change: transform;
  touch-action: none;
  user-select: none;
}

.slide-background {
  display: block;
  width: 100%;
  height: auto;
  pointer-events: none;

  &--is-slideable {
    $width: 150%;
    $overflow-width: $width - 100%;

    width: $width;
    margin-left: ($overflow-width / 2) * -1;
    margin-right: ($overflow-width / 2) * -1;
  }
}

.slide-content {
  position: absolute;
  left: 1rem;
  right: 1rem;
  bottom: 1rem;
  text-align: center;
  background: #fff;
}
</style>

// sveltekit-temp/src/routes/sensor-slide-component/+page.svelte
<script lang="ts">
  import { faker } from '@faker-js/faker';

  let containerElement;
  let imageElement;

  let translateX = 0; // todo make reactive

  function orientationChang(event): void {
    const rotationX = event.alpha; // y-axis

    const { width } = containerElement.getBoundingClientRect();

    const overflowSize = Math.abs(imageElement.offsetLeft);

    const maxTransformX = Math.round(overflowSize * 100 / width);
    const elongationFromCenterAbsolute = (rotationX * 100) / 180;

    const elongationFromCenterMappedToOverflowSize = (maxTransformX * elongationFromCenterAbsolute) / 100;

    translateX = elongationFromCenterMappedToOverflowSize;
  }

</script>

<svelte:window on:deviceorientation={orientationChang}/>

<section>
  <h2 class="text-xl pb-4">Sensor slide component</h2>
  <p class="pb-4">Rotation around the y-axis</p>
  <div class="m-0 p-0 overflow-hidden"
    style="--translateX: {translateX}%"
  >
    <figure
      bind:this={containerElement}
      class="relative select-none touch-none transform-gpu translate-x-[var(--translateX)]"
    >
      <img
        bind:this={imageElement}
        class="w-[150%] ml-[-25%] mr-[-25%] max-w-none pointer-events-none"
        src={faker.image.cats(800, 600, false)}
        alt="Cat"
      >
      <figcaption class="absolute inset-x-4 bottom-4 text-center bg-white">
        Meow!
      </figcaption>
    </figure>
  </div>
</section>
